#pragma once
#include <memory>
#include <vector>

class PrimeHelper
{
public:
    /**
     * @brief The limit used by <see cref="Primes"/> and <see cref="ExtendPrimesTo"/>, so that numbers under the limit are determined.
     * @return int
     */
    static int GetPrimeLimit();

    /**
     * @brief The primes generated by <see cref="ExtendPrimesTo"/> in order.
     * @return const std::vector<int>&
     */
    static const std::vector<int> &Primes();

    /**
     * @brief Euler's totient funcion, which counts the positive integers up to a given integer n that are relatively prime to n.
     *  <br/>if $n = \sum_i^s p_i^{k_i}$, then $\phi(n) = n \prod_i^s (1 - \frac{1}{p_i})$.
     * @param n
     * @return int
     */
    static int EulerPhi(int n);

    /**
     * @brief Check if a number is prime.
     * @param n
     * @return true
     * @return false
     */
    static bool IsPrime(int n);

    /**
     * @brief Push <see cref="PrimeLimit"/> to limit and extend the prime table <see cref="Primes"/>.
     * @param limit
     */
    static void ExtendPrimesTo(int limit);

private:
    static int PrimeLimit;
    static std::vector<int> _Primes;
};

namespace nth_prime
{
    int nth(size_t n);

} // namespace nth_prime
